const syllabus = [
  {area:'Processos Administrativos e Legislação', topics:[
    {id:'recrutamento-selecao',title:'Recrutamento e Seleção',body:`
      <h3>Visão geral</h3><p>Recrutamento e seleção pertencem ao processo de gestão de pessoas, mas cumprem funções diferentes. O recrutamento busca <b>atrair candidatos</b>; a seleção busca <b>comparar candidatos e escolher os mais adequados</b>.</p>
      <div class="diagram"><div class="flow"><span>Necessidade de pessoal</span><b>→</b><span>Recrutamento</span><b>→</b><span>Candidatos</span><b>→</b><span>Seleção</span><b>→</b><span>Admissão</span></div></div>
      <h3>Recrutamento</h3><p>É o conjunto de atividades voltadas à identificação e atração de pessoas potencialmente capazes de ocupar uma vaga. Pode ser interno, externo ou misto.</p>
      <table class="compare"><tr><th>Tipo</th><th>Origem dos candidatos</th><th>Pontos centrais</th></tr><tr><td>Interno</td><td>Quadro atual</td><td>Valoriza mobilidade e conhecimento prévio da organização.</td></tr><tr><td>Externo</td><td>Mercado</td><td>Amplia o universo de candidatos e pode trazer novas experiências.</td></tr><tr><td>Misto</td><td>Interno + externo</td><td>Combina as duas fontes.</td></tr></table>
      <h3>Seleção</h3><p>É a etapa em que a organização aplica critérios e instrumentos para comparar os candidatos. Entrevistas, testes, provas, análise curricular e dinâmicas podem compor o processo seletivo.</p>
      <div class="note"><b>Diferença fundamental:</b> divulgar vaga e buscar interessados é recrutamento; avaliar, comparar e decidir é seleção.</div>
      <div class="exam"><b>Como isso costuma aparecer em prova:</b> situações curtas em que a banca descreve divulgação de vaga, entrevista, teste técnico ou movimentação interna e pede para classificar a etapa.</div>
      <div class="memory"><b>O que precisa ficar na cabeça:</b> recrutamento atrai; seleção escolhe.</div>
      <h3>Glossário</h3><p><b>Candidato:</b> pessoa que concorre à vaga. <b>Fonte de recrutamento:</b> meio pelo qual os candidatos são alcançados. <b>Critério seletivo:</b> parâmetro usado para comparar candidatos.</p>`},
    {id:'cargos-carreira',title:'Plano de Cargos e Carreira',body:`<h3>Conceitos centrais</h3><p><b>Cargo</b> é um conjunto organizado de atribuições e responsabilidades. <b>Função</b> é o conjunto de atividades efetivamente desempenhadas. <b>Carreira</b> é a trajetória de desenvolvimento profissional ao longo do tempo.</p><table class="compare"><tr><th>Conceito</th><th>Pergunta que responde</th></tr><tr><td>Cargo</td><td>Qual posição estrutural existe?</td></tr><tr><td>Descrição de cargo</td><td>O que o cargo faz?</td></tr><tr><td>Especificação</td><td>O que se exige de quem ocupa?</td></tr><tr><td>Carreira</td><td>Como ocorre o desenvolvimento ao longo do tempo?</td></tr></table><div class="exam"><b>Como cai:</b> diferenças entre descrição e especificação; cargo e função; carreira e promoção.</div><div class="memory"><b>Fixe:</b> descrição = atribuições; especificação = requisitos.</div>`},
    {id:'treinamento-desenvolvimento',title:'Treinamento, Desenvolvimento e Educação',body:`<h3>Treinamento</h3><p>Direciona-se principalmente ao desempenho atual do trabalho: conhecimentos, habilidades e atitudes necessárias às atividades presentes.</p><h3>Desenvolvimento</h3><p>Tem horizonte mais amplo e de médio/longo prazo, preparando a pessoa para responsabilidades futuras e crescimento profissional.</p><h3>Educação corporativa</h3><p>Estrutura iniciativas de aprendizagem contínua alinhadas à estratégia organizacional.</p><div class="memory"><b>Fixe:</b> treinamento tende ao presente; desenvolvimento amplia capacidade futura.</div>`},
    {id:'desempenho-competencias',title:'Desempenho e Gestão por Competências',body:`<h3>Desempenho</h3><p>É a entrega observável de resultados e comportamentos no trabalho. A avaliação de desempenho compara expectativas com entregas e gera informação para desenvolvimento.</p><h3>Competências</h3><p>São combinações de conhecimentos, habilidades e atitudes mobilizadas para produzir resultados.</p><div class="diagram"><div class="flow"><span>Conhecimentos</span><b>+</b><span>Habilidades</span><b>+</b><span>Atitudes</span><b>→</b><span>Competência</span></div></div><p><b>Gap de competência</b> é a diferença entre o nível requerido e o nível existente.</p>`},
    {id:'relacoes-beneficios',title:'Relações de Trabalho e Benefícios',body:`<p>As relações de trabalho envolvem regras, direitos, deveres, comunicação institucional, negociação, ambiente de trabalho e mecanismos de proteção social. Benefícios integram a política de gestão de pessoas e podem possuir natureza legal ou organizacional.</p><div class="exam"><b>Como cai:</b> distinção entre remuneração, benefício, obrigação legal e política interna.</div>`},
    {id:'sgi',title:'Sistema de Gestão Integrado (SGI)',body:`<h3>O que é</h3><p>É a integração de sistemas e processos de gestão que antes poderiam funcionar separadamente. O objetivo é reduzir duplicidades, harmonizar controles e permitir visão sistêmica.</p><div class="diagram"><div class="flow"><span>Planejar</span><b>→</b><span>Executar</span><b>→</b><span>Verificar</span><b>→</b><span>Agir</span></div></div><h3>Auditoria e melhoria</h3><p>Auditoria interna verifica aderência a critérios. Não conformidades exigem tratamento; ações corretivas atuam sobre causas para evitar recorrência.</p><div class="memory"><b>Fixe:</b> correção trata o problema observado; ação corretiva trata a causa.</div>`},
    {id:'patrimonio',title:'Administração Patrimonial e Gestão de Ativos',body:`<p>Administração patrimonial controla bens da organização desde o registro até a baixa. Gestão de ativos amplia essa visão para valor, risco, desempenho e ciclo de vida.</p><div class="diagram"><div class="flow"><span>Aquisição</span><b>→</b><span>Registro</span><b>→</b><span>Uso</span><b>→</b><span>Manutenção</span><b>→</b><span>Avaliação</span><b>→</b><span>Baixa</span></div></div><p><b>Inventário</b> confere existência e condição. <b>Depreciação</b> reconhece a perda sistemática de valor econômico/contábil de determinados bens ao longo da vida útil.</p>`},
    {id:'manutencao',title:'Gestão da Manutenção',body:`<table class="compare"><tr><th>Tipo</th><th>Lógica</th></tr><tr><td>Corretiva</td><td>Intervir após falha ou perda de função.</td></tr><tr><td>Preventiva</td><td>Intervir antes da falha segundo plano/tempo/uso.</td></tr><tr><td>Preditiva</td><td>Monitorar condição para decidir o melhor momento de intervir.</td></tr></table><div class="exam"><b>Como cai:</b> a banca descreve uma situação operacional e pede o tipo de manutenção.</div>`},
    {id:'indicadores-esg',title:'Indicadores, KPIs e ESG',body:`<p>Indicadores transformam aspectos da operação em medidas acompanháveis. KPI é um indicador-chave ligado a objetivo relevante.</p><table class="compare"><tr><th>Eixo ESG</th><th>Exemplos de temas</th></tr><tr><td>Ambiental</td><td>Emissões, resíduos, energia, água.</td></tr><tr><td>Social</td><td>Segurança, pessoas, comunidades, diversidade.</td></tr><tr><td>Governança</td><td>Ética, controles, transparência, integridade.</td></tr></table>`}
  ]},
  {area:'Finanças e Contabilidade', topics:[
    {id:'mat-fin',title:'Matemática Financeira',body:`<h3>Porcentagem</h3><p>Uma taxa percentual expressa uma razão por 100. Em cálculos financeiros, a taxa deve ser compatível com o período.</p><h3>Juros simples</h3><p>Incidem sempre sobre o capital inicial: J = C·i·t e M = C + J.</p><h3>Juros compostos</h3><p>Incidem sobre o montante acumulado: M = C(1+i)^t.</p><div class="memory"><b>Fixe:</b> simples cresce linearmente; composto cresce multiplicativamente.</div>`},
    {id:'fundamentos-contabeis',title:'Fundamentos Contábeis',body:`<div class="diagram"><div class="flow"><span>Ativo</span><b>=</b><span>Passivo</span><b>+</b><span>Patrimônio Líquido</span></div></div><p><b>Ativo</b>: recursos/direitos controlados. <b>Passivo</b>: obrigações presentes. <b>Patrimônio líquido</b>: interesse residual após dedução dos passivos.</p><p>Receitas aumentam o patrimônio líquido por geração de benefícios econômicos; despesas o reduzem, exceto movimentações com proprietários.</p>`},
    {id:'obrigacoes-fiscais',title:'Obrigações Acessórias e Controle Fiscal',body:`<p>Além da obrigação principal de pagar tributos quando devidos, empresas cumprem deveres instrumentais de informar, registrar e escriturar. Sistemas digitais de escrituração integram parte desse controle.</p><div class="exam"><b>Como cai:</b> diferença entre obrigação principal e acessória; finalidade de escrituração e controles.</div>`},
    {id:'fluxo-caixa',title:'Fluxo de Caixa',body:`<p>Registra e analisa entradas e saídas de caixa e equivalentes. Os fluxos podem ser classificados em atividades operacionais, de investimento e de financiamento.</p><table class="compare"><tr><th>Classe</th><th>Exemplo</th></tr><tr><td>Operacional</td><td>Recebimentos de clientes e pagamentos do negócio.</td></tr><tr><td>Investimento</td><td>Compra ou venda de ativos de longo prazo.</td></tr><tr><td>Financiamento</td><td>Empréstimos, capital e remuneração de financiadores.</td></tr></table>`},
    {id:'bp-dre',title:'Balanço Patrimonial e DRE',body:`<h3>Balanço Patrimonial</h3><p>Retrata posição patrimonial em determinada data: ativo, passivo e patrimônio líquido.</p><h3>DRE</h3><p>Mostra a formação do resultado ao longo de um período, relacionando receitas e despesas.</p><div class="memory"><b>Fixe:</b> balanço = posição; DRE = desempenho no período.</div>`}
  ]},
  {area:'Logística e Gestão da Cadeia de Suprimentos', topics:[
    {id:'supply-chain',title:'Logística e Cadeia de Suprimentos',body:`<p>Logística coordena fluxos de materiais, informações e recursos para atender níveis de serviço. A cadeia de suprimentos integra fornecedores, organização, operadores e clientes.</p><div class="diagram"><div class="flow"><span>Fornecedor</span><b>→</b><span>Suprimentos</span><b>→</b><span>Operação</span><b>→</b><span>Distribuição</span><b>→</b><span>Cliente</span></div></div><p>Logística verde incorpora redução de impactos ambientais ao desenho desses fluxos.</p>`},
    {id:'modais',title:'Modalidades de Transporte',body:`<table class="compare"><tr><th>Modal</th><th>Traço geral</th></tr><tr><td>Rodoviário</td><td>Flexibilidade e capilaridade.</td></tr><tr><td>Ferroviário</td><td>Grandes volumes e longas distâncias.</td></tr><tr><td>Aquaviário</td><td>Elevada capacidade e menor velocidade.</td></tr><tr><td>Aéreo</td><td>Alta velocidade e custo elevado.</td></tr><tr><td>Dutoviário</td><td>Fluxo contínuo de produtos adequados.</td></tr></table><p><b>Multimodalidade</b> utiliza dois ou mais modais sob uma operação integrada com responsabilidade contratual própria.</p>`},
    {id:'estoques',title:'Gestão de Estoques',body:`<p>Estoques equilibram disponibilidade e custo. Conceitos centrais: estoque de segurança, ponto de pedido, lead time, nível de serviço, lote e classificação ABC.</p><div class="diagram"><div class="flow"><span>Consumo</span><b>→</b><span>Ponto de pedido</span><b>→</b><span>Reposição</span><b>→</b><span>Recebimento</span></div></div><p>A curva ABC prioriza controle conforme importância relativa, normalmente associada a valor de consumo.</p>`},
    {id:'armazenagem',title:'Armazenagem e Layout',body:`<p>Armazenagem organiza recebimento, endereçamento, guarda, separação e expedição. Layout eficiente reduz movimentação desnecessária e melhora segurança e produtividade.</p>`},
    {id:'manuseio',title:'Manuseio de Materiais',body:`<p>Movimentação deve buscar segurança, menor esforço, menor distância, melhor fluxo e uso adequado de equipamentos como empilhadeiras, paleteiras, transportadores e sistemas automatizados.</p>`},
    {id:'embalagem',title:'Embalagem e Unitização',body:`<p>Embalagem protege, identifica, facilita manuseio e pode contribuir para eficiência logística. Unitização agrupa volumes em unidade maior, como paletes ou contêineres.</p>`},
    {id:'compras',title:'Gestão de Compras',body:`<p>Compras envolvem planejamento da necessidade, especificação, orçamento, seleção de fornecedor, contratação e acompanhamento. O critério econômico deve respeitar requisitos técnicos e jurídicos.</p><div class="exam"><b>Atenção:</b> para estatais, a Lei 13.303/2016 é central. A Lei 14.133/2021 também integra o edital e deve ser estudada em sua redação vigente e em seus pontos de relação/diferença.</div>`},
    {id:'contratos',title:'Gestão de Contratos',body:`<div class="diagram"><div class="flow"><span>Planejamento</span><b>→</b><span>Contratação</span><b>→</b><span>Execução</span><b>→</b><span>Fiscalização</span><b>→</b><span>Encerramento</span></div></div><p>Gestão acompanha o contrato como um todo; fiscalização verifica a execução e conformidade. Riscos, alterações e aditivos devem ser formalmente tratados quando cabíveis.</p>`}
  ]},
  {area:'Noções de Informática', topics:[
    {id:'hardware-software',title:'Hardware, Software e Processadores',body:`<p><b>Hardware</b> é a parte física; <b>software</b> é o conjunto de programas e instruções. Processador executa instruções e coordena operações, enquanto memória e armazenamento têm papéis distintos.</p><table class="compare"><tr><th>Componente</th><th>Função geral</th></tr><tr><td>CPU</td><td>Processamento e controle.</td></tr><tr><td>RAM</td><td>Memória de trabalho volátil.</td></tr><tr><td>SSD/HDD</td><td>Armazenamento persistente.</td></tr></table>`},
    {id:'windows11',title:'Windows 11 e Arquivos',body:`<p>O Windows 11 organiza arquivos e pastas em sistemas de arquivos. Conceitos importantes: extensões, caminhos, atalhos, propriedades, copiar/mover/excluir, lixeira, compactação e pesquisa.</p>`},
    {id:'office',title:'Microsoft Office 2024',body:`<h3>Word</h3><p>Formatação, estilos, parágrafos, páginas, tabelas e revisão.</p><h3>Excel</h3><p>Fórmulas, funções, referências relativas e absolutas, filtros, ordenação e gráficos.</p><div class="note"><b>Referências:</b> A1 é relativa; $A$1 é absoluta; $A1 fixa coluna; A$1 fixa linha.</div><h3>PowerPoint</h3><p>Estrutura de apresentação, layouts, objetos, mídia e exibição.</p>`},
    {id:'internet-intranet',title:'Internet, Intranet e Navegadores',body:`<p>Internet é rede pública global de redes. Intranet utiliza tecnologias de rede em ambiente restrito da organização. Navegadores interpretam e exibem conteúdo web e gerenciam recursos como histórico, cache, downloads e extensões.</p>`},
    {id:'seguranca-lgpd',title:'Segurança da Informação e LGPD',body:`<h3>Segurança</h3><p>Princípios clássicos: confidencialidade, integridade e disponibilidade. Ameaças incluem phishing, malware, engenharia social e comprometimento de credenciais.</p><h3>LGPD</h3><p>Disciplina tratamento de dados pessoais. Conceitos essenciais: titular, dado pessoal, dado sensível, controlador, operador, encarregado, tratamento, bases legais e direitos do titular.</p><div class="memory"><b>Fixe:</b> controlador decide finalidades e meios essenciais do tratamento; operador atua em nome do controlador.</div>`}
  ]}
];

const nav=document.getElementById('nav'); const content=document.getElementById('content'); const tpl=document.getElementById('articleTemplate'); const search=document.getElementById('search');
const readSet=new Set(JSON.parse(localStorage.getItem('readTopics')||'[]'));
let currentId=null;
function buildNav(filter=''){
  nav.innerHTML=''; const q=filter.trim().toLowerCase();
  syllabus.forEach(group=>{const matching=group.topics.filter(t=>!q||t.title.toLowerCase().includes(q)||group.area.toLowerCase().includes(q)); if(!matching.length)return; const wrap=document.createElement('div'); wrap.className='nav-group'; wrap.innerHTML=`<h4>${group.area}</h4>`; matching.forEach(t=>{const b=document.createElement('button'); b.className='nav-item'; b.textContent=(readSet.has(t.id)?'✓ ':'')+t.title; b.onclick=()=>openTopic(group.area,t); if(currentId===t.id)b.classList.add('active'); wrap.appendChild(b)}); nav.appendChild(wrap)}); updateProgress();
}
function openTopic(area,t){currentId=t.id; const node=tpl.content.cloneNode(true); node.querySelector('[data-area]').textContent=area; node.querySelector('[data-title]').textContent=t.title; node.querySelector('[data-body]').innerHTML=t.body; const btn=node.querySelector('[data-read]'); if(readSet.has(t.id)){btn.textContent='Concluído ✓';btn.classList.add('done')} btn.onclick=()=>{if(readSet.has(t.id)){readSet.delete(t.id)}else{readSet.add(t.id)} localStorage.setItem('readTopics',JSON.stringify([...readSet])); openTopic(area,t); buildNav(search.value)}; content.innerHTML=''; content.appendChild(node); buildNav(search.value); window.scrollTo({top:0,behavior:'smooth'});}
function updateProgress(){const total=syllabus.reduce((n,g)=>n+g.topics.length,0); const pct=Math.round(readSet.size/total*100); document.getElementById('progressText').textContent=pct+'%'; document.getElementById('progressBar').style.width=pct+'%';}
search.oninput=e=>buildNav(e.target.value);
document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark'); localStorage.setItem('darkMode',document.body.classList.contains('dark')?'1':'0')}; if(localStorage.getItem('darkMode')==='1')document.body.classList.add('dark');
let fs=Number(localStorage.getItem('fontSize')||18); const applyFont=()=>document.documentElement.style.setProperty('--font',fs+'px'); applyFont(); document.getElementById('fontPlus').onclick=()=>{fs=Math.min(24,fs+1);localStorage.setItem('fontSize',fs);applyFont()};document.getElementById('fontMinus').onclick=()=>{fs=Math.max(15,fs-1);localStorage.setItem('fontSize',fs);applyFont()};
buildNav(); if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'))}
